submissions/chiconnect-laravel-web-app/routes/web.php
<?php

use App\Http\Controllers\AccountController;
use App\Http\Controllers\PayoutController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Route::get('/dashboard', [ProfileController::class, 'dashboard'])->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    /**
     * 
     *  ADMIN ROUTES
     * 
     * 
     */
    Route::group(['prefix' => 'user', 'as' => 'user.'], function () {
        /* Profiles */
        Route::get('profile', [ProfileController::class, 'index'])->name('profile.index');
        Route::get('profile/{user:uuid}', [ProfileController::class, 'show'])->name('profile.show');

        /* Account */
        Route::get('{user:uuid}/top-up', [AccountController::class, 'topUpForm'])->name('account.top-up-form');
        Route::post('top-up', [AccountController::class, 'topUp'])->name('account.top-up');
    });

    /**
     * 
     *  USER ROUTES
     * 
     */
    /* Payments */
    Route::group(['prefix' => 'payment', 'as' => 'payment.'], function () {
        /* Transfer */
        Route::group(['prefix' => 'transfer', 'as' => 'transfer.'], function () {
            Route::get('create', [AccountController::class, 'createTransfer'])->name('create');
            Route::post('process', [AccountController::class, 'processTransfer'])->name('process');
            Route::get('history', [AccountController::class, 'transferHistory'])->name('history');
        });

        /* Payout */
        Route::group(['prefix' => 'payout', 'as' => 'payout.'], function () {
            Route::get('history', [PayoutController::class, 'history'])->name('history');
            Route::get('airtime', [PayoutController::class, 'createAirtime'])->name('airtime.create');
            Route::get('bank', [PayoutController::class, 'createBank'])->name('bank.create');
        });
    });
});

require __DIR__ . '/auth.php';

submissions/chiconnect-laravel-web-app/app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

submissions/chiconnect-laravel-web-app/resources/views/transfer/create.blade.php
<x-app-layout>
    <div class="min-h-screen flex flex-col sm:justify-center items-center bg-gray-100">
        <div class="w-full sm:max-w-md px-6 py-4 bg-white shadow-md overflow-hidden sm:rounded-lg">
            <div class="w-full items-center flex justify-between mb-5">
                <div class="justify-self-start">
                    @if (!$balance)
                        <p class="font-bold text-red-500">Insufficient funds !!!</p>
                    @endif
                </div>
                <div class="justify-self-end font-semibold text-base tracking-wide text-slate-500">Balance:
                    ${{ number_format($balance ?? 0, 2) }}</div>
            </div>

            <!-- Session Status -->
            <div class="my-2">
                @if ($status = session('status'))
                    <div class='font-bold text-base text-green-600'>
                        {{ $status }}
                    </div>
                @endif
            </div>

            <!-- Error -->
            <div class="my-2">
                @if ($error = session('error'))
                    <div class='font-bold text-base text-red-600'>
                        {{ $error }}
                    </div>
                @endif
            </div>

            <form id="submit-form" method="POST" action="{{ route('payment.transfer.process') }}" autocomplete="off">
                @csrf
                <!-- Receiver -->
                <livewire:styles />
                <livewire:username />
                <livewire:scripts />

                <!-- Amount -->
                <div>
                    <x-input-label for="amount" :value="__('Amount')" />

                    <input type="number" id="amount" class="block mt-1 w-full" name="amount"
                        value="{{ old('amount') }}" min="1"
                        @if ($balance) max="{{ $balance }}" @endif required autofocus />

                    <x-input-error :messages="$errors->get('name')" class="mt-2" />
                </div>

                <div class="flex items-center justify-end mt-4">
                    <a id="go-back" class="justify-self-end underline text-sm text-gray-600 hover:text-gray-900"
                        href="{{ route('dashboard') }}">
                        {{ __('Go back') }}
                    </a>

                    @if ($balance)
                        <x-primary-button type="submit" id="send-button" class="ml-4">
                            {{ __('Send') }}
                        </x-primary-button>
                        <script>
                            document.getElementById("submit-form").addEventListener('submit', (event) => {
                                document.getElementById("send-button").disabled = true;
                                document.getElementById("send-button").innerHTML = "Processing...";
                                document.getElementById("go-back").innerHTML = '';
                            });
                        </script>
                    @endif
                </div>
            </form>
        </div>
    </div>
</x-app-layout>

submissions/chiconnect-laravel-web-app/resources/views/transfer/history.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Transfers
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <div class="w-full flex justify-end mb-5">
                        <a href="{{ route('payment.transfer.create') }}"
                            class="text-center hover:bg-purple-600 bg-purple-700 text-white font-bold p-1 px-3 rounded-lg">New transfer</a>
                    </div>
                    <div class="overflow-x-auto">
                        <table class="table table-auto w-full text-center">
                            <thead>
                                <tr class="border-b">
                                    <th class="p-2">#</th>
                                    <th class="p-2">Transaction ID</th>
                                    <th class="p-2">Amount ($)</th>
                                    <th class="p-2">From</th>
                                    <th class="p-2">To</th>
                                    <th class="p-2">Date</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse($transfers as $transfer)
                                    <tr class="hover:bg-gray-200 hover:cursor-pointer">
                                        <td class="p-2">
                                            {{ ($transfers->currentPage() - 1) * $transfers->perPage() + $loop->iteration }}
                                        </td>
                                        <td class="p-2">{{ $transfer->tnxID }}</td>
                                        <td class="p-2">{{ number_format($transfer->amount ?? 0, 2) }}</td>
                                        <td class="p-2">
                                            @php
                                                $from = $transfer->from->username ?? 'unknown';
                                                echo $from == auth()->user()->username ? 'me' : $from;
                                            @endphp
                                        </td>
                                        <td class="p-2">
                                            @php
                                                $from = $transfer->to->username ?? 'unknown';
                                                echo $from == auth()->user()->username ? 'me' : $from;
                                            @endphp
                                        </td>
                                        <td class="p-2">{{ $transfer->created_at }}</td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td class="p-2" colspan="6">
                                            <center>No transfers yet!</center>
                                        </td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                        <div class="my-3">
                            {{ $transfers->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>